version: 1

models:
  - name: dw_weather
    description: "DW layer for weather data"
    config:
      materialized: incremental
      order_by: startTime
      unique_key: startTime,locationName
    columns:
      - name: startTime
        description: "Start time of the weather data"
        tests:
          - not_null:
              config:
                severity: error
      - name: endTime
        description: "End time of the weather data"
        tests:
          - not_null:
              config:
                severity: warn
      - name: locationName
        description: "Location name of the weather data"
        tests:
          - not_null:
              config:
                severity: warn
      - name: minTemperature
        description: "Minimum temperature name of the weather data"
        tests:
          - not_null:
              config:
                severity: warn
      - name: maxTemperature
        description: "Maximum temperature name of the weather data"
        tests:
          - not_null:
              config:
                severity: warn
      - name: comfortIndex
        description: "Comfort index name of the weather data"
        tests:
          - not_null:
              config:
                severity: warn
