version: 1

models:
  - name: weather
    description: "Weather summary table"
    config:
      schema: "dm"
      materialized: incremental
      order_by: date
      unique_key: date,locationName
    columns:
      - name: date
        description: "Date of the weather data"
        tests:
          - not_null:
              config:
                severity: error
      - name: locationName
        description: "Location name"
        tests:
          - not_null:
              config:
                severity: error
      - name: weatherValue
        description: "Weather value"
        tests:
          - not_null:
              config:
                severity: warn
      - name: weatherPhenomenon
        description: "Weather name"
        tests:
          - not_null:
              config:
                severity: warn
      - name: minTemperature
        description: "Minimum temperature name"
        tests:
          - not_null:
              config:
                severity: warn
      - name: maxTemperature
        description: "Maximum temperature name"
        tests:
          - not_null:
              config:
                severity: warn
      - name: comfortIndex
        description: "Comfort index name"
        tests:
          - not_null:
              config:
                severity: warn
